/* Password gate for encrypted artifact pages (generated by build.py).
 *
 * The published page holds nothing but ciphertext. On a correct password we
 * decrypt it and swap in the real document.
 *
 * The swap uses document.open()/write()/close(), NOT innerHTML. innerHTML does
 * not execute <script> tags, so the July 2026 attempt left every interactive
 * page dead after unlock (fullscreen toggles, tabs, the React app on
 * tariff-trade-breakdown). document.write runs them exactly as a normal load.
 */
(function () {
  'use strict';

  const C = window.PagesCrypto;

  const gate = document.getElementById('password-gate');
  const input = document.getElementById('password-input');
  const msg = document.getElementById('password-msg');

  const payloadEl = document.getElementById('pg-payload');
  const keysEl = document.getElementById('pg-unlock-keys');

  const payload = payloadEl ? payloadEl.textContent : '';

  let unlockKeys = {};
  try {
    unlockKeys = JSON.parse(keysEl ? keysEl.textContent : '{}') || {};
  } catch (e) {
    unlockKeys = {};
  }

  function say(text, cls) {
    if (!msg) return;
    msg.textContent = text || '';
    msg.className = 'msg' + (cls ? ' ' + cls : '');
  }

  /* Seed whatever localStorage keys the decrypted page's own gate checks, so it
   * unlocks itself on first script execution instead of prompting again. */
  function seedUnlockKeys() {
    try {
      Object.keys(unlockKeys).forEach(function (k) {
        localStorage.setItem(k, unlockKeys[k]);
      });
    } catch (e) {
      /* storage disabled — the inlined pre-hide style still covers the gate */
    }
  }

  function boot(html) {
    seedUnlockKeys();
    // Replace the entire document. Scripts in `html` execute as on a fresh load.
    document.open();
    document.write(html);
    document.close();
  }

  async function attempt(password, opts) {
    const silent = opts && opts.silent;
    if (!silent) say('Decrypting…', 'busy');

    const html = await C.decrypt(payload, password);
    if (!html) return false;

    C.storePassword(password);
    boot(html);
    return true;
  }

  async function onSubmit() {
    const value = input ? input.value.trim() : '';
    if (!value) return;

    if (input) input.disabled = true;
    const ok = await attempt(value);
    if (!ok) {
      if (input) {
        input.disabled = false;
        input.value = '';
        input.focus();
      }
      say('Incorrect password.', 'error');
    }
  }

  if (input) {
    input.addEventListener('keydown', function (e) {
      if (e.key === 'Enter') onSubmit();
    });
  }

  // Returning visitor: decrypt straight away with the stored password.
  (async function () {
    const stored = C.getStoredPassword();
    if (!stored) return;

    const ok = await attempt(stored, { silent: true });
    if (!ok) {
      // Password rotated since this visitor last unlocked
      C.clearStoredPassword();
      if (gate) gate.style.display = '';
    }
  })();
})();
